name: Build Unibot

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore Unibot.sln
      
    - name: Build solution
      run: dotnet build Unibot.sln --configuration Release --no-restore
      
    - name: Test (if tests exist)
      run: dotnet test Unibot.sln --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
    - name: Publish application
      run: dotnet publish Unibot/Unibot.csproj --configuration Release --output ./publish --no-build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unibot-build-${{ github.sha }}
        path: |
          ./publish/
          !./publish/*.pdb
        retention-days: 30
        
    - name: Create release package (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        Compress-Archive -Path ./publish/* -DestinationPath Unibot-${{ github.ref_name }}.zip
        
    - name: Create GitHub Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Unibot-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}